// LOADER
export const SET_LOADER_CONTEXT = "SET_LOADER_CONTEXT";

// COLOR THeme
export const SET_COLOR_THEME_LIGHT = "SET_COLOR_THEME_LIGHT";
export const SET_COLOR_THEME_DARK = "SET_COLOR_THEME_DARK";
